update docker within docker

diff --git a/docker-within-docker-aws-cli/Dockerfile b/docker-within-docker-aws-cli/Dockerfile
--- a/docker-within-docker-aws-cli/Dockerfile
+++ b/docker-within-docker-aws-cli/Dockerfile
@@ -1,9 +1,58 @@
-FROM docker:17.06.0-ce-git
-MAINTAINER Dragos Bulugean
+FROM node:8.14.0-alpine
+
+RUN apk add --no-cache \
+    ca-certificates
+
+# set up nsswitch.conf for Go's "netgo" implementation (which Docker explicitly uses)
+# - https://github.com/docker/docker-ce/blob/v17.09.0-ce/components/engine/hack/make.sh#L149
+# - https://github.com/golang/go/blob/go1.9.1/src/net/conf.go#L194-L275
+# - docker run --rm debian:stretch grep '^hosts:' /etc/nsswitch.conf
+RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf
+
+ENV DOCKER_CHANNEL stable
+ENV DOCKER_VERSION 18.09.0
+# TODO ENV DOCKER_SHA256
+# https://github.com/docker/docker-ce/blob/5b073ee2cf564edee5adca05eee574142f7627bb/components/packaging/static/hash_files !!
+# (no SHA file artifacts on download.docker.com yet as of 2017-06-07 though)
+
+RUN set -eux; \
+    \
+    # this "case" statement is generated via "update.sh"
+    apkArch="$(apk --print-arch)"; \
+    case "$apkArch" in \
+    x86_64) dockerArch='x86_64' ;; \
+    armhf) dockerArch='armel' ;; \
+    aarch64) dockerArch='aarch64' ;; \
+    ppc64le) dockerArch='ppc64le' ;; \
+    s390x) dockerArch='s390x' ;; \
+    *) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+    esac; \
+    \
+    if ! wget -O docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
+    echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+    exit 1; \
+    fi; \
+    \
+    tar --extract \
+    --file docker.tgz \
+    --strip-components 1 \
+    --directory /usr/local/bin/ \
+    ; \
+    rm docker.tgz; \
+    \
+    dockerd --version; \
+    docker --version
+
+COPY modprobe.sh /usr/local/bin/modprobe
+COPY docker-entrypoint.sh /usr/local/bin/
 
 RUN apk --no-cache update && \
-    apk add ca-certificates wget && \
+    apk add ca-certificates && \
     update-ca-certificates && \
-    apk --no-cache add python py-pip py-setuptools ca-certificates groff less && \
+    apk --no-cache add wget python py-pip py-setuptools ca-certificates groff less && \
     pip --no-cache-dir install awscli && \
     rm -rf /var/cache/apk/*
+
+ENTRYPOINT ["docker-entrypoint.sh"]
+CMD ["sh"]
+
